export const USERDATA = 'USERDATA'
export const USERREMOVEDATA = 'USERREMOVEDATA'
export const USERAVATAR = 'USERAVATAR'

export const DIRECTION = 'DIRECTION'
export const REMOVEDIRECTION = 'REMOVEDIRECTION'

export const DETAILSTRAVEL = 'DETAILSTRAVEL'
export const REMOVEDETAILSTRAVEL = 'REMOVEDETAILSTRAVEL'

export const LOCATION = 'LOCATION'
export const REMOVELOCATION = 'REMOVELOCATION'

export const ACTIVETRAVEL = 'ACTIVETRAVEL'
export const REMOVEACTIVETRAVEL = 'REMOVEACTIVETRAVEL'

export const TRAVEL = 'TRAVEL'
export const COMMERCES = 'COMMERCES'
export const SERVICES = 'SERVICES'
export const DRIVERS = 'DRIVERS'
export const FAVORITE = 'FAVORITE'
export const REMOVETRAVEL = 'REMOVETRAVEL'
export const ADDRESS = 'ADDRESS'
export const REMOVEADDRESS = 'REMOVEADDRESS'
